/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header per la classe tum_andrive_Andrive */


#ifndef _Included_tum_andrive_LaneDetection_LaneDetector
#define _Included_tum_andrive_LaneDetection_LaneDetector
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_tum_andrive_lanedetection_LaneDetector_mainDelegate
  (JNIEnv *env, jobject obj, jlong in, jlong out, jint houghValue);


#ifdef __cplusplus
}
#endif
#endif
