/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tum_andrive_Andrive */

#ifndef _Included_tum_andrive_Andrive
#define _Included_tum_andrive_Andrive
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_tum_andrive_Andrive_nativeThreshold
  (JNIEnv *, jobject, jlong, jlong);

JNIEXPORT void JNICALL Java_tum_andrive_Andrive_nativeCannyEdge
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
